package com.genscript.gsscm.common.constant;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "SpecDropDownListName")
@XmlEnum
public enum SpecDropDownListName {

	@XmlEnumValue("CUSTOMER_ROLE")
	CUSTOMER_ROLE("CUSTOMER_ROLE"), @XmlEnumValue("DEPARTMENT_FUNCTION")
	DEPARTMENT_FUNCTION("DEPARTMENT_FUNCTION"), @XmlEnumValue("ORIGINAL_SOURCE")
	ORIGINAL_SOURCE("ORIGINAL_SOURCE"), @XmlEnumValue("ORGANIZATION_CATEGORY")
	ORGANIZATION_CATEGORY("ORGANIZATION_CATEGORY"), @XmlEnumValue("ORGANIZATION_TYPE")
	ORGANIZATION_TYPE("ORGANIZATION_TYPE"), @XmlEnumValue("LANGUAGE_CODE")
	LANGUAGE_CODE("LANGUAGE_CODE"), @XmlEnumValue("TIME_ZONE")
	TIME_ZONE("TIME_ZONE"), @XmlEnumValue("CREDIT_LIMIT")
	CREDIT_LIMIT("CREDIT_LIMIT"), @XmlEnumValue("SHIP_METHOD")
	SHIP_METHOD("SHIP_METHOD"), @XmlEnumValue("CURRENCY")
	CURRENCY("CURRENCY"), @XmlEnumValue("QUOTE_MEMO_TEMPLATE")
	QUOTE_MEMO_TEMPLATE("QUOTE_MEMO_TEMPLATE"), @XmlEnumValue("ORDER_MEMO_TEMPLATE")
	ORDER_MEMO_TEMPLATE("ORDER_MEMO_TEMPLATE"), @XmlEnumValue("SALES_CONTACT")
	SALES_CONTACT("SALES_CONTACT"), @XmlEnumValue("PROMOTION_CODE")
	PROMOTION_CODE("PROMOTION_CODE"), @XmlEnumValue("COUPON_CODE")
	COUPON_CODE("COUPON_CODE"), @XmlEnumValue("PB_DEPARTMENT")
	PB_DEPARTMENT("PB_DEPARTMENT"), @XmlEnumValue("DECIPLINE_INTEREST")
	DECIPLINE_INTEREST("DECIPLINE_INTEREST"), @XmlEnumValue("APPLICATION_INTEREST")
	APPLICATION_INTEREST("APPLICATION_INTEREST"), @XmlEnumValue("SALES_TERRITORY")
	SALES_TERRITORY("SALES_TERRITORY"), @XmlEnumValue("SALES_GROUP")
	SALES_TERRITORY_OTHER("SALES_TERRITORY_OTHER"), @XmlEnumValue("SALES_TERRITORY_OTHER")
	SALES_GROUP("SALES_GROUP"), @XmlEnumValue("PICK_LOCATION")
	PICK_LOCATION("PICK_LOCATION"), @XmlEnumValue("TECH_SUPPORT")
	TECH_SUPPORT("TECH_SUPPORT"), @XmlEnumValue("PROJECT_SUPPORT")
	PROJECT_SUPPORT("PROJECT_SUPPORT"), @XmlEnumValue("PRODUCT_CLASSIFICATION")
	PRODUCT_CLASSIFICATION("PRODUCT_CLASSIFICATION"), @XmlEnumValue("SERVICE_CLASSIFICATION")
	SERVICE_CLASSIFICATION("SERVICE_CLASSIFICATION"), @XmlEnumValue("TAX_STATUS_NATIONAL")
	TAX_STATUS_NATIONAL("TAX_STATUS_NATIONAL"), @XmlEnumValue("TAX_STATUS_STATE")
	TAX_STATUS_STATE("TAX_STATUS_STATE"), @XmlEnumValue("PACKAGE_TYPE")
	PACKAGE_TYPE("PACKAGE_TYPE"), @XmlEnumValue("TAX_STATUS_COUNTRY")
	TAX_STATUS_COUNTRY("TAX_STATUS_COUNTRY"), @XmlEnumValue("PRICE_CATALOG")
	PRICE_CATALOG("PRICE_CATALOG"), @XmlEnumValue("QUOTE_TYPE")
	QUOTE_TYPE("QUOTE_TYPE"), @XmlEnumValue("ORDER_TYPE")
	ORDER_TYPE("ORDER_TYPE"), @XmlEnumValue("SEQUENCE")
	SEQUENCE("SEQUENCE"), @XmlEnumValue("QUOTE_STATUS_LIST")
	QUOTE_STATUS_LIST("QUOTE_STATUS_LIST"), @XmlEnumValue("ORDER_STATUS_LIST")
	ORDER_STATUS_LIST("ORDER_STATUS_LIST"), @XmlEnumValue("RFM_VALUE")
	RFM_VALUE("RFM_VALUE"), @XmlEnumValue("TERRITORY")
	TERRITORY("TERRITORY"), @XmlEnumValue("CATEGORY")
	CATEGORY("CATEGORY"), @XmlEnumValue("HOST_EXPS_ORGANISM")
	HOST_EXPS_ORGANISM("HOST_EXPS_ORGANISM"), @XmlEnumValue("VECTOR")
	VECTOR("VECTOR"), @XmlEnumValue("CATALOG")
	CATALOG("CATALOG"), @XmlEnumValue("COUNTRY_NAME")
	COUNTRY_NAME("COUNTRY_NAME"), @XmlEnumValue("SHIP_CARRIERS")
	SHIP_CARRIERS("SHIP_CARRIERS"), @XmlEnumValue("SHIP_ZONE")
	SHIP_ZONE("SHIP_ZONE"), @XmlEnumValue("COMPR_SHIP_METHOD")
	COMPR_SHIP_METHOD("COMPR_SHIP_METHOD"), @XmlEnumValue("WAREHOUSE")
	WAREHOUSE("WAREHOUSE"), @XmlEnumValue("RATE_LIST")
	RATE_LIST("RATE_LIST"), @XmlEnumValue("PEPTIDE_QUANTITY")
	PEPTIDE_QUANTITY("PEPTIDE_QUANTITY"),@XmlEnumValue("PEPTIDE_PURITY_ARRAY")
	PEPTIDE_PURITY_ARRAY("PEPTIDE_PURITY_ARRAY"), @XmlEnumValue("PEPTIDE_PURITY")
	PEPTIDE_PURITY("PEPTIDE_PURITY"), @XmlEnumValue("N_TERMINAL")
	N_TERMINAL("N_TERMINAL"), @XmlEnumValue("C_TERMINAL")
	C_TERMINAL("C_TERMINAL"), @XmlEnumValue("MODIFICATION")
	MODIFICATION("MODIFICATION"), @XmlEnumValue("COUNTRY_CODE")
	COUNTRY_CODE("COUNTRY_CODE"), @XmlEnumValue("SERVICE_ATTRIBUTE_MAPPING_OPERATOR")
	SERVICE_ATTRIBUTE_MAPPING_OPERATOR("SERVICE_ATTRIBUTE_MAPPING_OPERATOR"), @XmlEnumValue("DEFINE_FORMULA_ARGUMENT_TYPE")
	DEFINE_FORMULA_ARGUMENT_TYPE("DEFINE_FORMULA_ARGUMENT_TYPE"), @XmlEnumValue("PRICE_RULE_OPERATION")
	PRICE_RULE_OPERATION("PRICE_RULE_OPERATION"), @XmlEnumValue("ALL_DEPARTMENTS")
	ALL_DEPARTMENTS("ALL_DEPARTMENTS"), // add by zhou gang 2011 7 19 update for
										// customer >case> Potential Liability
										// add departments from
										// system.department
	@XmlEnumValue("MAIL_GROUP_FUNCTION")
	MAIL_GROUP_FUNCTION("MAIL_GROUP_FUNCTION"),
	@XmlEnumValue("ALL_COUNTRY")ALL_COUNTRY("ALL_COUNTRY"),	
	@XmlEnumValue("GET_ALLSALES_MANAGER")
	GET_ALLSALES_MANAGER("GET_ALLSALES_MANAGER"), 
	
	@XmlEnumValue("GET_ALLTECHACCOUNT_MANAGER")
	GET_ALLTECHACCOUNT_MANAGER("GET_ALLTECHACCOUNT_MANAGER"), 
	
	@XmlEnumValue("GET_ALLPROJECT_MANAGER")
	GET_ALLPROJECT_MANAGER("GET_ALLPROJECT_MANAGER"),

	@XmlEnumValue("GET_PRIMER_NAME")
	GET_PRIMER_NAME("GET_PRIMER_NAME"), 
	
	@XmlEnumValue("GET_ALLORDER_STATUS")
	GET_ALLORDER_STATUS("GET_ALLORDER_STATUS"), @XmlEnumValue("CASE_SEND_EMAILTO")
	CASE_SEND_EMAILTO("CASE_SEND_EMAILTO");
	// add by zhou gang 2011 7 19 update for
	// customer >case>Send Email To

	private final String value;

	SpecDropDownListName(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static SpecDropDownListName fromValue(String v) {
		for (SpecDropDownListName c : SpecDropDownListName.values()) {
			if (c.value.equals(v)) {
				return c;

			}
		}
		throw new IllegalArgumentException(v);
	}

}
