
/*
 * 
 */

package com.genscript.gsscm.epicorwebservice.stub.part;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Wed May 04 11:20:50 CST 2011
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "PartService", 
                  wsdlLocation = "file:/D:/temp/PartService.asmx.wsdl",
                  targetNamespace = "http://epicor.com/webservices/") 
public class PartService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://epicor.com/webservices/", "PartService");
    public final static QName PartServiceSoap12 = new QName("http://epicor.com/webservices/", "PartServiceSoap12");
    public final static QName PartServiceSoap = new QName("http://epicor.com/webservices/", "PartServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://10.168.2.131/EpicorServices/PartService.asmx?WSDL");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://10.168.2.131/EpicorServices/PartService.asmx?WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PartService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PartService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns PartServiceSoap
     */
    @WebEndpoint(name = "PartServiceSoap12")
    public PartServiceSoap getPartServiceSoap12() {
        return super.getPort(PartServiceSoap12, PartServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PartServiceSoap
     */
    @WebEndpoint(name = "PartServiceSoap12")
    public PartServiceSoap getPartServiceSoap12(WebServiceFeature... features) {
        return super.getPort(PartServiceSoap12, PartServiceSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns PartServiceSoap
     */
    @WebEndpoint(name = "PartServiceSoap")
    public PartServiceSoap getPartServiceSoap() {
        return super.getPort(PartServiceSoap, PartServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PartServiceSoap
     */
    @WebEndpoint(name = "PartServiceSoap")
    public PartServiceSoap getPartServiceSoap(WebServiceFeature... features) {
        return super.getPort(PartServiceSoap, PartServiceSoap.class, features);
    }

}
