
/*
 * 
 */

package com.genscript.gsscm.epicorwebservice.stub.customer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Tue May 10 14:12:33 CST 2011
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "CustomerService", 
                  wsdlLocation = "file:/D:/CustomerService.asmx.xml",
                  targetNamespace = "http://epicor.com/webservices/") 
public class CustomerService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://epicor.com/webservices/", "CustomerService");
    public final static QName CustomerServiceSoap12 = new QName("http://epicor.com/webservices/", "CustomerServiceSoap12");
    public final static QName CustomerServiceSoap = new QName("http://epicor.com/webservices/", "CustomerServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://10.168.2.131/EpicorServices/CustomerService.asmx?WSDL");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://10.168.2.131/EpicorServices/CustomerService.asmx?WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CustomerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns CustomerServiceSoap
     */
    @WebEndpoint(name = "CustomerServiceSoap12")
    public CustomerServiceSoap getCustomerServiceSoap12() {
        return super.getPort(CustomerServiceSoap12, CustomerServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerServiceSoap
     */
    @WebEndpoint(name = "CustomerServiceSoap12")
    public CustomerServiceSoap getCustomerServiceSoap12(WebServiceFeature... features) {
        return super.getPort(CustomerServiceSoap12, CustomerServiceSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns CustomerServiceSoap
     */
    @WebEndpoint(name = "CustomerServiceSoap")
    public CustomerServiceSoap getCustomerServiceSoap() {
        return super.getPort(CustomerServiceSoap, CustomerServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerServiceSoap
     */
    @WebEndpoint(name = "CustomerServiceSoap")
    public CustomerServiceSoap getCustomerServiceSoap(WebServiceFeature... features) {
        return super.getPort(CustomerServiceSoap, CustomerServiceSoap.class, features);
    }

}
