package com.genscript.gsscm.epicorwebservice.stub.invoice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2011-12-01T09:45:54.748+08:00
 * Generated source version: 2.3.7
 * 
 */
@WebService(targetNamespace = "http://epicor.com/webservices/", name = "InvoiceIStatTrnServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface InvoiceIStatTrnServiceSoap {

    @RequestWrapper(localName = "UpdateIStatTrn", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.invoice.UpdateIStatTrn")
    @WebMethod(operationName = "UpdateIStatTrn", action = "http://epicor.com/webservices/UpdateIStatTrn")
    @ResponseWrapper(localName = "UpdateIStatTrnResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.invoice.UpdateIStatTrnResponse")
    public void updateIStatTrn(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ds", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType ds,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "UpdateIStatTrnResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<InvoiceIStatTrnDataSetType> updateIStatTrnResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    /**
     * <br><div>The <font color=#336699><b><i>APGetInvoiceIStatTrn</i></b></font> Web method accepts the following arguments:<ul type=circle style="padding-left:20px"><li>The vendor number of the invoice detail line (ParameterInfo)<li>The invoice number of the invoice detail line (ParameterInfo)<li>The line number of the invoice detail line (ParameterInfo)<li>This flag indicates that this function is called for Tracker (ParameterInfo)</ul><br><b>Returns:</b>  The InvoiceIStatTrn data set (InvoiceIStatTrnDataSet)</div>
     */
    @RequestWrapper(localName = "APGetInvoiceIStatTrn", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.invoice.APGetInvoiceIStatTrn")
    @WebMethod(operationName = "APGetInvoiceIStatTrn", action = "http://epicor.com/webservices/APGetInvoiceIStatTrn")
    @ResponseWrapper(localName = "APGetInvoiceIStatTrnResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.invoice.APGetInvoiceIStatTrnResponse")
    public void apGetInvoiceIStatTrn(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "inVendorNum", targetNamespace = "http://epicor.com/webservices/")
        int inVendorNum,
        @WebParam(name = "inInvoiceNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String inInvoiceNum,
        @WebParam(name = "inInvoiceLine", targetNamespace = "http://epicor.com/webservices/")
        int inInvoiceLine,
        @WebParam(name = "forTracker", targetNamespace = "http://epicor.com/webservices/")
        boolean forTracker,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "APGetInvoiceIStatTrnResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<InvoiceIStatTrnDataSetType> apGetInvoiceIStatTrnResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    /**
     * <br><div>The <font color=#336699><b><i>ARGetInvoiceIStatTrn</i></b></font> Web method accepts the following arguments:<ul type=circle style="padding-left:20px"><li>The invoice number of the invoice detail line (ParameterInfo)<li>The line number of the invoice detail line (ParameterInfo)<li>This flag indicates that this function is called for Tracker (ParameterInfo)</ul><br><b>Returns:</b>  The InvoiceIStatTrn data set (InvoiceIStatTrnDataSet)</div>
     */
    @RequestWrapper(localName = "ARGetInvoiceIStatTrn", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.invoice.ARGetInvoiceIStatTrn")
    @WebMethod(operationName = "ARGetInvoiceIStatTrn", action = "http://epicor.com/webservices/ARGetInvoiceIStatTrn")
    @ResponseWrapper(localName = "ARGetInvoiceIStatTrnResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.invoice.ARGetInvoiceIStatTrnResponse")
    public void arGetInvoiceIStatTrn(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "inInvoiceNum", targetNamespace = "http://epicor.com/webservices/")
        int inInvoiceNum,
        @WebParam(name = "inInvoiceLine", targetNamespace = "http://epicor.com/webservices/")
        int inInvoiceLine,
        @WebParam(name = "forTracker", targetNamespace = "http://epicor.com/webservices/")
        boolean forTracker,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "ARGetInvoiceIStatTrnResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<InvoiceIStatTrnDataSetType> arGetInvoiceIStatTrnResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "ChangeCommodityCode", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.invoice.ChangeCommodityCode")
    @WebMethod(operationName = "ChangeCommodityCode", action = "http://epicor.com/webservices/ChangeCommodityCode")
    @ResponseWrapper(localName = "ChangeCommodityCodeResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.invoice.ChangeCommodityCodeResponse")
    public void changeCommodityCode(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "proposedCommodityCode", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String proposedCommodityCode,
        @WebParam(name = "ds", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType ds,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "ChangeCommodityCodeResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<InvoiceIStatTrnDataSetType> changeCommodityCodeResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "ChangeFOB", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.invoice.ChangeFOB")
    @WebMethod(operationName = "ChangeFOB", action = "http://epicor.com/webservices/ChangeFOB")
    @ResponseWrapper(localName = "ChangeFOBResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.invoice.ChangeFOBResponse")
    public void changeFOB(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "proposedFOB", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String proposedFOB,
        @WebParam(name = "ds", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType ds,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "ChangeFOBResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<InvoiceIStatTrnDataSetType> changeFOBResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "ChangeShipVia", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.invoice.ChangeShipVia")
    @WebMethod(operationName = "ChangeShipVia", action = "http://epicor.com/webservices/ChangeShipVia")
    @ResponseWrapper(localName = "ChangeShipViaResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.invoice.ChangeShipViaResponse")
    public void changeShipVia(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "proposedShipViaCode", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String proposedShipViaCode,
        @WebParam(name = "ds", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType ds,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "ChangeShipViaResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<InvoiceIStatTrnDataSetType> changeShipViaResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );
}
