
package com.genscript.gsscm.epicorwebservice.stub.invoice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2011-12-01T09:45:54.673+08:00
 * Generated source version: 2.3.7
 * 
 */
public final class InvoiceIStatTrnServiceSoap_InvoiceIStatTrnServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://epicor.com/webservices/", "InvoiceIStatTrnService");

    private InvoiceIStatTrnServiceSoap_InvoiceIStatTrnServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = InvoiceIStatTrnService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        InvoiceIStatTrnService ss = new InvoiceIStatTrnService(wsdlURL, SERVICE_NAME);
        InvoiceIStatTrnServiceSoap port = ss.getInvoiceIStatTrnServiceSoap12();  
        
        {
        System.out.println("Invoking updateIStatTrn...");
        java.lang.String _updateIStatTrn_companyID = "";
        com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType _updateIStatTrn_ds = null;
        com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType _updateIStatTrn_callContextIn = null;
        javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType> _updateIStatTrn_updateIStatTrnResult = new javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType>();
        javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType> _updateIStatTrn_callContextOut = new javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType>();
        port.updateIStatTrn(_updateIStatTrn_companyID, _updateIStatTrn_ds, _updateIStatTrn_callContextIn, _updateIStatTrn_updateIStatTrnResult, _updateIStatTrn_callContextOut);

        System.out.println("updateIStatTrn._updateIStatTrn_updateIStatTrnResult=" + _updateIStatTrn_updateIStatTrnResult.value);
        System.out.println("updateIStatTrn._updateIStatTrn_callContextOut=" + _updateIStatTrn_callContextOut.value);

        }
        {
        System.out.println("Invoking apGetInvoiceIStatTrn...");
        java.lang.String _apGetInvoiceIStatTrn_companyID = "";
        int _apGetInvoiceIStatTrn_inVendorNum = 0;
        java.lang.String _apGetInvoiceIStatTrn_inInvoiceNum = "";
        int _apGetInvoiceIStatTrn_inInvoiceLine = 0;
        boolean _apGetInvoiceIStatTrn_forTracker = false;
        com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType _apGetInvoiceIStatTrn_callContextIn = null;
        javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType> _apGetInvoiceIStatTrn_apGetInvoiceIStatTrnResult = new javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType>();
        javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType> _apGetInvoiceIStatTrn_callContextOut = new javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType>();
        port.apGetInvoiceIStatTrn(_apGetInvoiceIStatTrn_companyID, _apGetInvoiceIStatTrn_inVendorNum, _apGetInvoiceIStatTrn_inInvoiceNum, _apGetInvoiceIStatTrn_inInvoiceLine, _apGetInvoiceIStatTrn_forTracker, _apGetInvoiceIStatTrn_callContextIn, _apGetInvoiceIStatTrn_apGetInvoiceIStatTrnResult, _apGetInvoiceIStatTrn_callContextOut);

        System.out.println("apGetInvoiceIStatTrn._apGetInvoiceIStatTrn_apGetInvoiceIStatTrnResult=" + _apGetInvoiceIStatTrn_apGetInvoiceIStatTrnResult.value);
        System.out.println("apGetInvoiceIStatTrn._apGetInvoiceIStatTrn_callContextOut=" + _apGetInvoiceIStatTrn_callContextOut.value);

        }
        {
        System.out.println("Invoking arGetInvoiceIStatTrn...");
        java.lang.String _arGetInvoiceIStatTrn_companyID = "";
        int _arGetInvoiceIStatTrn_inInvoiceNum = 0;
        int _arGetInvoiceIStatTrn_inInvoiceLine = 0;
        boolean _arGetInvoiceIStatTrn_forTracker = false;
        com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType _arGetInvoiceIStatTrn_callContextIn = null;
        javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType> _arGetInvoiceIStatTrn_arGetInvoiceIStatTrnResult = new javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType>();
        javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType> _arGetInvoiceIStatTrn_callContextOut = new javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType>();
        port.arGetInvoiceIStatTrn(_arGetInvoiceIStatTrn_companyID, _arGetInvoiceIStatTrn_inInvoiceNum, _arGetInvoiceIStatTrn_inInvoiceLine, _arGetInvoiceIStatTrn_forTracker, _arGetInvoiceIStatTrn_callContextIn, _arGetInvoiceIStatTrn_arGetInvoiceIStatTrnResult, _arGetInvoiceIStatTrn_callContextOut);

        System.out.println("arGetInvoiceIStatTrn._arGetInvoiceIStatTrn_arGetInvoiceIStatTrnResult=" + _arGetInvoiceIStatTrn_arGetInvoiceIStatTrnResult.value);
        System.out.println("arGetInvoiceIStatTrn._arGetInvoiceIStatTrn_callContextOut=" + _arGetInvoiceIStatTrn_callContextOut.value);

        }
        {
        System.out.println("Invoking changeCommodityCode...");
        java.lang.String _changeCommodityCode_companyID = "";
        java.lang.String _changeCommodityCode_proposedCommodityCode = "";
        com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType _changeCommodityCode_ds = null;
        com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType _changeCommodityCode_callContextIn = null;
        javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType> _changeCommodityCode_changeCommodityCodeResult = new javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType>();
        javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType> _changeCommodityCode_callContextOut = new javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType>();
        port.changeCommodityCode(_changeCommodityCode_companyID, _changeCommodityCode_proposedCommodityCode, _changeCommodityCode_ds, _changeCommodityCode_callContextIn, _changeCommodityCode_changeCommodityCodeResult, _changeCommodityCode_callContextOut);

        System.out.println("changeCommodityCode._changeCommodityCode_changeCommodityCodeResult=" + _changeCommodityCode_changeCommodityCodeResult.value);
        System.out.println("changeCommodityCode._changeCommodityCode_callContextOut=" + _changeCommodityCode_callContextOut.value);

        }
        {
        System.out.println("Invoking changeFOB...");
        java.lang.String _changeFOB_companyID = "";
        java.lang.String _changeFOB_proposedFOB = "";
        com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType _changeFOB_ds = null;
        com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType _changeFOB_callContextIn = null;
        javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType> _changeFOB_changeFOBResult = new javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType>();
        javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType> _changeFOB_callContextOut = new javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType>();
        port.changeFOB(_changeFOB_companyID, _changeFOB_proposedFOB, _changeFOB_ds, _changeFOB_callContextIn, _changeFOB_changeFOBResult, _changeFOB_callContextOut);

        System.out.println("changeFOB._changeFOB_changeFOBResult=" + _changeFOB_changeFOBResult.value);
        System.out.println("changeFOB._changeFOB_callContextOut=" + _changeFOB_callContextOut.value);

        }
        {
        System.out.println("Invoking changeShipVia...");
        java.lang.String _changeShipVia_companyID = "";
        java.lang.String _changeShipVia_proposedShipViaCode = "";
        com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType _changeShipVia_ds = null;
        com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType _changeShipVia_callContextIn = null;
        javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType> _changeShipVia_changeShipViaResult = new javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.InvoiceIStatTrnDataSetType>();
        javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType> _changeShipVia_callContextOut = new javax.xml.ws.Holder<com.genscript.gsscm.epicorwebservice.stub.invoice.CallContextDataSetType>();
        port.changeShipVia(_changeShipVia_companyID, _changeShipVia_proposedShipViaCode, _changeShipVia_ds, _changeShipVia_callContextIn, _changeShipVia_changeShipViaResult, _changeShipVia_callContextOut);

        System.out.println("changeShipVia._changeShipVia_changeShipViaResult=" + _changeShipVia_changeShipViaResult.value);
        System.out.println("changeShipVia._changeShipVia_callContextOut=" + _changeShipVia_callContextOut.value);

        }

        System.exit(0);
    }

}
