
package com.genscript.gsscm.epicorwebservice.stub.invoice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2011-12-07T13:20:57.625+08:00
 * Generated source version: 2.3.7
 * 
 */
public final class ServiceSoap_ServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.genscript.com/", "Service");

    private ServiceSoap_ServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Service ss = new Service(wsdlURL, SERVICE_NAME);
        ServiceSoap port = ss.getServiceSoap12();  
        
        {
        System.out.println("Invoking getPaymentList...");
        javax.xml.datatype.XMLGregorianCalendar _getPaymentList_tranDate = null;
        com.genscript.gsscm.epicorwebservice.stub.invoice.ArrayOfPayment _getPaymentList__return = port.getPaymentList(_getPaymentList_tranDate);
        System.out.println("getPaymentList.result=" + _getPaymentList__return);


        }
        {
        System.out.println("Invoking getInvoiceList...");
        javax.xml.datatype.XMLGregorianCalendar _getInvoiceList_changeDate = null;
        com.genscript.gsscm.epicorwebservice.stub.invoice.ArrayOfInvoice _getInvoiceList__return = port.getInvoiceList(_getInvoiceList_changeDate);
        System.out.println("getInvoiceList.result=" + _getInvoiceList__return);


        }

        System.exit(0);
    }

}
