package com.genscript.gsscm.epicorwebservice.stub.invoice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2011-12-07T13:20:57.640+08:00
 * Generated source version: 2.3.7
 * 
 */
@WebService(targetNamespace = "http://www.genscript.com/", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    /**
     * <br><div> 返回所传参数日期的付款信息（如果参数为null则返回当天的付款信息）<ul><li><b>参数:</b> <font color=#336699><b>DateTime</b></font> tranDate</li><li><b>返回:</b> paymentInfoDataSet</li></ui></div>
     */
    @WebResult(name = "getPaymentListResult", targetNamespace = "http://www.genscript.com/")
    @RequestWrapper(localName = "getPaymentList", targetNamespace = "http://www.genscript.com/", className = "com.genscript.GetPaymentList")
    @WebMethod(action = "http://www.genscript.com/getPaymentList")
    @ResponseWrapper(localName = "getPaymentListResponse", targetNamespace = "http://www.genscript.com/", className = "com.genscript.GetPaymentListResponse")
    public com.genscript.gsscm.epicorwebservice.stub.invoice.ArrayOfPayment getPaymentList(
        @WebParam(name = "tranDate", targetNamespace = "http://www.genscript.com/")
        javax.xml.datatype.XMLGregorianCalendar tranDate
    );

    /**
     * <br><div> 返回所传参数日期的发票信息（如果参数为null则返回当天的发票信息）<ul><li><b>参数:</b> <font color=#336699><b>DateTime</b></font> changeDate</li><li><b>返回:</b> invoiceInfoDataSet</li></ui></div>
     */
    @WebResult(name = "getInvoiceListResult", targetNamespace = "http://www.genscript.com/")
    @RequestWrapper(localName = "getInvoiceList", targetNamespace = "http://www.genscript.com/", className = "com.genscript.GetInvoiceList")
    @WebMethod(action = "http://www.genscript.com/getInvoiceList")
    @ResponseWrapper(localName = "getInvoiceListResponse", targetNamespace = "http://www.genscript.com/", className = "com.genscript.GetInvoiceListResponse")
    public com.genscript.gsscm.epicorwebservice.stub.invoice.ArrayOfInvoice getInvoiceList(
        @WebParam(name = "changeDate", targetNamespace = "http://www.genscript.com/")
        javax.xml.datatype.XMLGregorianCalendar changeDate
    );
}
