package com.genscript.gsscm.epicorwebservice.stub.lot;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Wed Aug 24 10:20:01 CST 2011
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://epicor.com/webservices/", name = "LotSelectUpdateServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface LotSelectUpdateServiceSoap {

    @RequestWrapper(localName = "Update", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.UpdateResponse")
    @WebMethod(operationName = "Update", action = "http://epicor.com/webservices/Update")
    public void update(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "LotSelectUpdateData", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.LotSelectUpdateDataSetType lotSelectUpdateData,
        @WebParam(name = "continueProcessingOnError", targetNamespace = "http://epicor.com/webservices/")
        boolean continueProcessingOnError,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "UpdateResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<LotSelectUpdateDataSetType> updateResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "errorsOccurred", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> errorsOccurred,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetByID", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.GetByID")
    @ResponseWrapper(localName = "GetByIDResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.GetByIDResponse")
    @WebMethod(operationName = "GetByID", action = "http://epicor.com/webservices/GetByID")
    public void getByID(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "partNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String partNum,
        @WebParam(name = "lotNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String lotNum,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetByIDResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<LotSelectUpdateDataSetType> getByIDResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "CheckDupLotNum", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.CheckDupLotNum")
    @ResponseWrapper(localName = "CheckDupLotNumResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.CheckDupLotNumResponse")
    @WebMethod(operationName = "CheckDupLotNum", action = "http://epicor.com/webservices/CheckDupLotNum")
    public void checkDupLotNum(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "vLotNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String vLotNum,
        @WebParam(name = "vPartNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String vPartNum,
        @WebParam(name = "vRowid", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String vRowid,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "CheckDupLotNumResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> checkDupLotNumResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "vMessage", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> vMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetNewPartLot", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.GetNewPartLot")
    @ResponseWrapper(localName = "GetNewPartLotResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.GetNewPartLotResponse")
    @WebMethod(operationName = "GetNewPartLot", action = "http://epicor.com/webservices/GetNewPartLot")
    public void getNewPartLot(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ds", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.LotSelectUpdateDataSetType ds,
        @WebParam(name = "partNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String partNum,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetNewPartLotResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<LotSelectUpdateDataSetType> getNewPartLotResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "DeleteByID", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.DeleteByID")
    @ResponseWrapper(localName = "DeleteByIDResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.DeleteByIDResponse")
    @WebMethod(operationName = "DeleteByID", action = "http://epicor.com/webservices/DeleteByID")
    public void deleteByID(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "partNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String partNum,
        @WebParam(name = "lotNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String lotNum,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "DeleteByIDResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> deleteByIDResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetNewPartLotAttch", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.GetNewPartLotAttch")
    @ResponseWrapper(localName = "GetNewPartLotAttchResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.GetNewPartLotAttchResponse")
    @WebMethod(operationName = "GetNewPartLotAttch", action = "http://epicor.com/webservices/GetNewPartLotAttch")
    public void getNewPartLotAttch(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ds", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.LotSelectUpdateDataSetType ds,
        @WebParam(name = "partNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String partNum,
        @WebParam(name = "lotNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String lotNum,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetNewPartLotAttchResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<LotSelectUpdateDataSetType> getNewPartLotAttchResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "ChkForNeedsLotAttrs", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.ChkForNeedsLotAttrs")
    @ResponseWrapper(localName = "ChkForNeedsLotAttrsResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.ChkForNeedsLotAttrsResponse")
    @WebMethod(operationName = "ChkForNeedsLotAttrs", action = "http://epicor.com/webservices/ChkForNeedsLotAttrs")
    public void chkForNeedsLotAttrs(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "pcPartNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String pcPartNum,
        @WebParam(name = "pcLotNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String pcLotNum,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "ChkForNeedsLotAttrsResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> chkForNeedsLotAttrsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "needsLotAttrs", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> needsLotAttrs,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GenerateNewLotNum", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.GenerateNewLotNum")
    @ResponseWrapper(localName = "GenerateNewLotNumResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.GenerateNewLotNumResponse")
    @WebMethod(operationName = "GenerateNewLotNum", action = "http://epicor.com/webservices/GenerateNewLotNum")
    public void generateNewLotNum(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "vPartNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String vPartNum,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GenerateNewLotNumResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> generateNewLotNumResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "vNewLotNum", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> vNewLotNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "ValidateLotAttributes", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.ValidateLotAttributes")
    @ResponseWrapper(localName = "ValidateLotAttributesResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.ValidateLotAttributesResponse")
    @WebMethod(operationName = "ValidateLotAttributes", action = "http://epicor.com/webservices/ValidateLotAttributes")
    public void validateLotAttributes(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ds", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.LotSelectUpdateDataSetType ds,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "ValidateLotAttributesResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<LotSelectUpdateDataSetType> validateLotAttributesResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetRows", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.GetRows")
    @ResponseWrapper(localName = "GetRowsResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.GetRowsResponse")
    @WebMethod(operationName = "GetRows", action = "http://epicor.com/webservices/GetRows")
    public void getRows(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "whereClausePartLot", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String whereClausePartLot,
        @WebParam(name = "whereClausePartLotAttch", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String whereClausePartLotAttch,
        @WebParam(name = "pageSize", targetNamespace = "http://epicor.com/webservices/")
        int pageSize,
        @WebParam(name = "absolutePage", targetNamespace = "http://epicor.com/webservices/")
        int absolutePage,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetRowsResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<LotSelectUpdateDataSetType> getRowsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "morePages", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> morePages,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetList", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.GetList")
    @ResponseWrapper(localName = "GetListResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.lot.GetListResponse")
    @WebMethod(operationName = "GetList", action = "http://epicor.com/webservices/GetList")
    public void getList(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "whereClause", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String whereClause,
        @WebParam(name = "pageSize", targetNamespace = "http://epicor.com/webservices/")
        int pageSize,
        @WebParam(name = "absolutePage", targetNamespace = "http://epicor.com/webservices/")
        int absolutePage,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.lot.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetListResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<PartLotListDataSetType> getListResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "morePages", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> morePages,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );
}
