package com.genscript.gsscm.epicorwebservice.stub.inventory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Jul 22 16:32:02 CST 2011
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://epicor.com/webservices/", name = "InventoryQtyAdjServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface InventoryQtyAdjServiceSoap {

    @RequestWrapper(localName = "ValidateSN", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.ValidateSN")
    @ResponseWrapper(localName = "ValidateSNResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.ValidateSNResponse")
    @WebMethod(operationName = "ValidateSN", action = "http://epicor.com/webservices/ValidateSN")
    public void validateSN(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ds", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.InventoryQtyAdjDataSetType ds,
        @WebParam(name = "serialNumber", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String serialNumber,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "ValidateSNResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<InventoryQtyAdjDataSetType> validateSNResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "isVoided", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> isVoided,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetSelectSerialNumbersParams", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetSelectSerialNumbersParams")
    @ResponseWrapper(localName = "GetSelectSerialNumbersParamsResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetSelectSerialNumbersParamsResponse")
    @WebMethod(operationName = "GetSelectSerialNumbersParams", action = "http://epicor.com/webservices/GetSelectSerialNumbersParams")
    public void getSelectSerialNumbersParams(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ds", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.InventoryQtyAdjDataSetType ds,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetSelectSerialNumbersParamsResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<SelectSerialNumbersParamsDataSetType> getSelectSerialNumbersParamsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "NegativeInventoryTest", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.NegativeInventoryTest")
    @ResponseWrapper(localName = "NegativeInventoryTestResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.NegativeInventoryTestResponse")
    @WebMethod(operationName = "NegativeInventoryTest", action = "http://epicor.com/webservices/NegativeInventoryTest")
    public void negativeInventoryTest(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "pcPartNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String pcPartNum,
        @WebParam(name = "pcWhseCode", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String pcWhseCode,
        @WebParam(name = "pcBinNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String pcBinNum,
        @WebParam(name = "pcLotNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String pcLotNum,
        @WebParam(name = "pcDimCode", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String pcDimCode,
        @WebParam(name = "pdDimConvFactor", targetNamespace = "http://epicor.com/webservices/")
        java.math.BigDecimal pdDimConvFactor,
        @WebParam(name = "pdTranQty", targetNamespace = "http://epicor.com/webservices/")
        java.math.BigDecimal pdTranQty,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "NegativeInventoryTestResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> negativeInventoryTestResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "pcNeqQtyAction", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> pcNeqQtyAction,
        @WebParam(mode = WebParam.Mode.OUT, name = "pcMessage", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> pcMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetMfgPartFromRowID", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetMfgPartFromRowID")
    @ResponseWrapper(localName = "GetMfgPartFromRowIDResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetMfgPartFromRowIDResponse")
    @WebMethod(operationName = "GetMfgPartFromRowID", action = "http://epicor.com/webservices/GetMfgPartFromRowID")
    public void getMfgPartFromRowID(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ipRowType", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String ipRowType,
        @WebParam(name = "ipRowID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String ipRowID,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetMfgPartFromRowIDResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> getMfgPartFromRowIDResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "opPartNum", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opPartNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "opMfgNum", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Integer> opMfgNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "opMfgPartNum", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opMfgPartNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetCustNumFromRowID", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetCustNumFromRowID")
    @ResponseWrapper(localName = "GetCustNumFromRowIDResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetCustNumFromRowIDResponse")
    @WebMethod(operationName = "GetCustNumFromRowID", action = "http://epicor.com/webservices/GetCustNumFromRowID")
    public void getCustNumFromRowID(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ipRowType", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String ipRowType,
        @WebParam(name = "ipRowID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String ipRowID,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetCustNumFromRowIDResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> getCustNumFromRowIDResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "opPartNum", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opPartNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "opCustNum", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Integer> opCustNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "SetInventoryQtyAdj", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.SetInventoryQtyAdj")
    @ResponseWrapper(localName = "SetInventoryQtyAdjResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.SetInventoryQtyAdjResponse")
    @WebMethod(operationName = "SetInventoryQtyAdj", action = "http://epicor.com/webservices/SetInventoryQtyAdj")
    public void setInventoryQtyAdj(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ds", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.InventoryQtyAdjDataSetType ds,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "SetInventoryQtyAdjResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<InventoryQtyAdjDataSetType> setInventoryQtyAdjResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "partTranPKs", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> partTranPKs,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetPartXRefInfo", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetPartXRefInfo")
    @ResponseWrapper(localName = "GetPartXRefInfoResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetPartXRefInfoResponse")
    @WebMethod(operationName = "GetPartXRefInfo", action = "http://epicor.com/webservices/GetPartXRefInfo")
    public void getPartXRefInfo(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(mode = WebParam.Mode.INOUT, name = "partNum", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> partNum,
        @WebParam(name = "sysRowID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String sysRowID,
        @WebParam(name = "rowType", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String rowType,
        @WebParam(mode = WebParam.Mode.INOUT, name = "uomCode", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> uomCode,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetPartXRefInfoResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> getPartXRefInfoResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "serialWarning", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> serialWarning,
        @WebParam(mode = WebParam.Mode.OUT, name = "questionString", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> questionString,
        @WebParam(mode = WebParam.Mode.OUT, name = "multipleMatch", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> multipleMatch,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetInventoryQtyAdjBrw", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetInventoryQtyAdjBrw")
    @ResponseWrapper(localName = "GetInventoryQtyAdjBrwResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetInventoryQtyAdjBrwResponse")
    @WebMethod(operationName = "GetInventoryQtyAdjBrw", action = "http://epicor.com/webservices/GetInventoryQtyAdjBrw")
    public void getInventoryQtyAdjBrw(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "partNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String partNum,
        @WebParam(name = "wareHouseCode", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String wareHouseCode,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetInventoryQtyAdjBrwResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<InventoryQtyAdjBrwDataSetType> getInventoryQtyAdjBrwResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "primaryBin", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> primaryBin,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetInventoryQtyAdj", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetInventoryQtyAdj")
    @ResponseWrapper(localName = "GetInventoryQtyAdjResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetInventoryQtyAdjResponse")
    @WebMethod(operationName = "GetInventoryQtyAdj", action = "http://epicor.com/webservices/GetInventoryQtyAdj")
    public void getInventoryQtyAdj(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "partnumber", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String partnumber,
        @WebParam(name = "uomCode", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String uomCode,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetInventoryQtyAdjResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<InventoryQtyAdjDataSetType> getInventoryQtyAdjResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "CheckSN", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.CheckSN")
    @ResponseWrapper(localName = "CheckSNResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.CheckSNResponse")
    @WebMethod(operationName = "CheckSN", action = "http://epicor.com/webservices/CheckSN")
    public void checkSN(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "partNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String partNum,
        @WebParam(name = "warehouseCode", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String warehouseCode,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "CheckSNResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> checkSNResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "serialNumbersRequired", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> serialNumbersRequired,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "PreSetInventoryQtyAdj", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.PreSetInventoryQtyAdj")
    @ResponseWrapper(localName = "PreSetInventoryQtyAdjResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.PreSetInventoryQtyAdjResponse")
    @WebMethod(operationName = "PreSetInventoryQtyAdj", action = "http://epicor.com/webservices/PreSetInventoryQtyAdj")
    public void preSetInventoryQtyAdj(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ds", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.InventoryQtyAdjDataSetType ds,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "PreSetInventoryQtyAdjResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<InventoryQtyAdjDataSetType> preSetInventoryQtyAdjResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "requiresUserInput", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> requiresUserInput,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "FindPart", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.FindPart")
    @ResponseWrapper(localName = "FindPartResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.FindPartResponse")
    @WebMethod(operationName = "FindPart", action = "http://epicor.com/webservices/FindPart")
    public void findPart(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ipPartNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String ipPartNum,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "FindPartResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> findPartResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "opPartNum", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opPartNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "opUOM", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opUOM,
        @WebParam(mode = WebParam.Mode.OUT, name = "opMatchType", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opMatchType,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "KitPartStatus", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.KitPartStatus")
    @ResponseWrapper(localName = "KitPartStatusResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.KitPartStatusResponse")
    @WebMethod(operationName = "KitPartStatus", action = "http://epicor.com/webservices/KitPartStatus")
    public void kitPartStatus(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "partNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String partNum,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "KitPartStatusResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> kitPartStatusResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "kitMessage", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> kitMessage,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetPartFromRowID", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetPartFromRowID")
    @ResponseWrapper(localName = "GetPartFromRowIDResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetPartFromRowIDResponse")
    @WebMethod(operationName = "GetPartFromRowID", action = "http://epicor.com/webservices/GetPartFromRowID")
    public void getPartFromRowID(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ipRowType", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String ipRowType,
        @WebParam(name = "ipRowID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String ipRowID,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetPartFromRowIDResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> getPartFromRowIDResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "opPartNum", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opPartNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "opUOM", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opUOM,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "GetAvailTranDocTypes", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetAvailTranDocTypes")
    @ResponseWrapper(localName = "GetAvailTranDocTypesResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.GetAvailTranDocTypesResponse")
    @WebMethod(operationName = "GetAvailTranDocTypes", action = "http://epicor.com/webservices/GetAvailTranDocTypes")
    public void getAvailTranDocTypes(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetAvailTranDocTypesResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> getAvailTranDocTypesResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "listAvailTranDocTypes", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> listAvailTranDocTypes,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "FindPartAndGetRowID", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.FindPartAndGetRowID")
    @ResponseWrapper(localName = "FindPartAndGetRowIDResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.FindPartAndGetRowIDResponse")
    @WebMethod(operationName = "FindPartAndGetRowID", action = "http://epicor.com/webservices/FindPartAndGetRowID")
    public void findPartAndGetRowID(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ipPartNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String ipPartNum,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "FindPartAndGetRowIDResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> findPartAndGetRowIDResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "opPartNum", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opPartNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "opUOM", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opUOM,
        @WebParam(mode = WebParam.Mode.OUT, name = "opMatchType", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opMatchType,
        @WebParam(mode = WebParam.Mode.OUT, name = "opRowID", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opRowID,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );

    @RequestWrapper(localName = "FindFirstPart", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.FindFirstPart")
    @ResponseWrapper(localName = "FindFirstPartResponse", targetNamespace = "http://epicor.com/webservices/", className = "com.genscript.gsscm.epicorwebservice.stub.inventory.FindFirstPartResponse")
    @WebMethod(operationName = "FindFirstPart", action = "http://epicor.com/webservices/FindFirstPart")
    public void findFirstPart(
        @WebParam(name = "CompanyID", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String companyID,
        @WebParam(name = "ipPartNum", targetNamespace = "http://epicor.com/webservices/")
        java.lang.String ipPartNum,
        @WebParam(name = "ipCustNum", targetNamespace = "http://epicor.com/webservices/")
        int ipCustNum,
        @WebParam(name = "callContextIn", targetNamespace = "http://epicor.com/webservices/")
        com.genscript.gsscm.epicorwebservice.stub.inventory.CallContextDataSetType callContextIn,
        @WebParam(mode = WebParam.Mode.OUT, name = "FindFirstPartResult", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.Boolean> findFirstPartResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "opPartNum", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opPartNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "opUOM", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opUOM,
        @WebParam(mode = WebParam.Mode.OUT, name = "opMatchType", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opMatchType,
        @WebParam(mode = WebParam.Mode.OUT, name = "opRowID", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<java.lang.String> opRowID,
        @WebParam(mode = WebParam.Mode.OUT, name = "callContextOut", targetNamespace = "http://epicor.com/webservices/")
        javax.xml.ws.Holder<CallContextDataSetType> callContextOut
    );
}
