
/*
 * 
 */

package com.genscript.gsscm.epicorwebservice.stub.inventory;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Jul 22 16:32:02 CST 2011
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "InventoryQtyAdjService", 
                  wsdlLocation = "file:InventoryQtyAdjService.asmx.xml",
                  targetNamespace = "http://epicor.com/webservices/") 
public class InventoryQtyAdjService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://epicor.com/webservices/", "InventoryQtyAdjService");
    public final static QName InventoryQtyAdjServiceSoap = new QName("http://epicor.com/webservices/", "InventoryQtyAdjServiceSoap");
    public final static QName InventoryQtyAdjServiceSoap12 = new QName("http://epicor.com/webservices/", "InventoryQtyAdjServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://10.168.2.131/EpicorServices/InventoryQtyAdjService.asmx?WSDL");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://10.168.2.131/EpicorServices/InventoryQtyAdjService.asmx.xml");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public InventoryQtyAdjService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InventoryQtyAdjService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InventoryQtyAdjService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns InventoryQtyAdjServiceSoap
     */
    @WebEndpoint(name = "InventoryQtyAdjServiceSoap")
    public InventoryQtyAdjServiceSoap getInventoryQtyAdjServiceSoap() {
        return super.getPort(InventoryQtyAdjServiceSoap, InventoryQtyAdjServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventoryQtyAdjServiceSoap
     */
    @WebEndpoint(name = "InventoryQtyAdjServiceSoap")
    public InventoryQtyAdjServiceSoap getInventoryQtyAdjServiceSoap(WebServiceFeature... features) {
        return super.getPort(InventoryQtyAdjServiceSoap, InventoryQtyAdjServiceSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns InventoryQtyAdjServiceSoap
     */
    @WebEndpoint(name = "InventoryQtyAdjServiceSoap12")
    public InventoryQtyAdjServiceSoap getInventoryQtyAdjServiceSoap12() {
        return super.getPort(InventoryQtyAdjServiceSoap12, InventoryQtyAdjServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventoryQtyAdjServiceSoap
     */
    @WebEndpoint(name = "InventoryQtyAdjServiceSoap12")
    public InventoryQtyAdjServiceSoap getInventoryQtyAdjServiceSoap12(WebServiceFeature... features) {
        return super.getPort(InventoryQtyAdjServiceSoap12, InventoryQtyAdjServiceSoap.class, features);
    }

}
