package com.genscript.gsscm.epicorwebservice.stub.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Tue Nov 01 11:04:17 CST 2011
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    @WebResult(name = "getPaymentListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getPaymentList", targetNamespace = "http://tempuri.org/", className = "com.genscript.gsscm.epicorwebservice.stub.service.GetPaymentList")
    @ResponseWrapper(localName = "getPaymentListResponse", targetNamespace = "http://tempuri.org/", className = "com.genscript.gsscm.epicorwebservice.stub.service.GetPaymentListResponse")
    @WebMethod(action = "http://tempuri.org/getPaymentList")
    public com.genscript.gsscm.epicorwebservice.stub.service.ArrayOfPayment getPaymentList(
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar date
    );
}
